version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.flask  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #ports:
      #- "5000:5000"
  busybox:
    image: "yauritux/busybox-curl"
